[package]
name = "spark-connect-rs"
version = "0.0.1-beta"
edition = "2021"
license = "Apache-2.0"
description = "Apache Spark Connect Client for Rust"
keywords = ["spark", "spark_connect"]
documentation = "https://docs.rs/spark-connect-rs"
readme = "README.md"
homepage = "https://github.com/sjrusso8/spark-connect-rs"
repository = "https://github.com/sjrusso8/spark-connect-rs"
include = [
    "build.rs",
    "docker-compose.yml",
    "examples/**/*",
    "src/**/*",
    "spark/connector/connect/common/src/main/protobuf/spark/**/*",
]

[dependencies]
tonic = { version ="0.11.0"}
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-rustls = "0.25.0"

arrow = { version = "50.0.0", features = ["prettyprint"] }
arrow-ipc = "50.0.0"

prost = "0.12.0"
prost-types = "0.12.0"

rand = "0.8.5"
uuid = { version = "1.4.1", features = ["v4"] }
url = "2.2"


[build-dependencies]
tonic-build = "0.11.0"

[lib]
doctest = false

[[example]]
name = "reader"

[[example]]
name = "sql"

[[example]]
name = "writer"
