/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsDataFrame = DataFrame
export class DataFrame {
  constructor()
  select(cols: Array<string>): DataFrame
  filter(expr: string): DataFrame
  count(): Promise<number>
  show(): Promise<void>
}
export type JsSparkSession = SparkSession
export class SparkSession {
  static build(conn: string): Promise<JsSparkSession>
  sql(query: string): Promise<DataFrame>
}
