name: build

on:
  push:
    branches: [main, "v*", "dev"]
  pull_request:
    branches: [main, "v*", "dev"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: install protoc
        uses: arduino/setup-protoc@v2
        with:
          version: 23.x

      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Format
        run: cargo fmt -- --check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: install protoc
        uses: arduino/setup-protoc@v2
        with:
          version: 23.x

      - name: install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: build and lint with clippy
        run: cargo clippy

      - name: Check docs
        run: cargo doc

      - name: Check no default features (except rustls)
        run: cargo check

  integration_test:
    name: integration tests
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      # Disable full debug symbol generation to speed up CI build and keep memory down
      # <https://doc.rust-lang.org/cargo/reference/profiles.html>
      RUSTFLAGS: "-C debuginfo=line-tables-only"
      # https://github.com/rust-lang/cargo/issues/10280
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUST_BACKTRACE: "1"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: install protoc
        uses: arduino/setup-protoc@v2
        with:
          version: 23.x

      - name: install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Start emulated services
        run: docker-compose up -d

      - name: Run tests
        run: cargo test -p spark-connect-core --features polars,datafusion
